<header>
    <div class="header-container">
        <a href="#" id = "aboutBrand">О БРЕНДЕ</a>
        <a href="/tournamentScore">NBA ТАБЛИЦА</a>
        <a href="mailto:rahmatullin.damir21@gmail.com?subject=Связаться со мной">ЗАДАТЬ ВОПРОС</a>
        <a href="/"><img class="logo" src="/images/logo.png" alt="Ballin Logo"></a>
        <a href="/giftCertificate">ПОДАРОЧНЫЙ СЕРТИФИКАТ</a>
        <a href="/profile">ПРОФИЛЬ</a>
    </div>
</header>